### ISSUE TITLE
IdsDatagrid: Error on drag/drop text on Column Header Filter 

### ISSUE THREAD

**Issue by GMInf** [infor-design/enterprise-wc#1276]
**Describe the bug**
Selecting and dragging text to the column header filter results in runtime error.

**To Reproduce**

1. Run enterprise-wc
2. Select the DATA GRID text and begin drag
3. Drop to Color or Product Id column header filter
4. See error:
```
Cannot read properties of undefined (reading 'id')
TypeError: Cannot read properties of undefined (reading 'id')
    at IdsDataGrid.moveColumn (webpack-internal:///./src/components/ids-data-grid/ids-data-grid.ts:468:80)
    at IdsDataGridHeader.eval (webpack-internal:///./src/components/ids-data-grid/ids-data-grid-header.ts:186:22)
```

**Expected behavior**
Column header filter input should have the value of dropped text.

**Version**
- enterprise-wc: 1.0.0-beta.9

**Screenshots**

https://github.com/infor-design/enterprise-wc/assets/53523076/dbea552a-3f60-445e-9e03-3ccc90b0cf9f

**Platform**
Infor Application/Team Name: M3 UX
OS Version: Windows 11
Browser Name: chrome
Browser Version: 109.0.5414.75 (Official Build) (64-bit)

**Additional context**

**Comment by tmcconechy** [comment]
@GMInf how do i drag the text?

**Comment by jbrcna** [comment]
QA Passed. moving this to done

**Comment by GMInf** [comment]
Thanks for looking into this. I found that our application have an overlapping drag and drop event handler that is preventing the drop on the filter input.
Yes the color changes on hover. Confirming that there are no issues on the drag/drop of text, working on the header filter input on beta 11.

**Comment by GMInf** [comment]
Yes, it is working on our application now. Needed code changes on our side so it won't affect the text drop on the column header input.
