### ISSUE TITLE
IdsSplitter: Initialization Errors

### ISSUE THREAD

**Issue by pwpatton** [infor-design/enterprise-wc#2590]
**Describe the bug**
2 issues here. the first is more important

1. when using a collapsed data binding the splitter size isn't respected, it gets set at 50% instead of the 25% indicated.
2. There is also an issue where a `this.parentNode.initialized` fails because `parentNode` is null (let me know if this should be in a separate ticket).

**To Reproduce**

1st Issue
1. Go to enterprise-wc-examples repo
2. cd in the angular-ids-wc directory, npm install, npm run start
3. Go to http://localhost:4200/ids-splitter/responsive-splitter
4. Notice that while I set the size of the left-pane to 25% the splitter seems to be displaying at "50%"

2nd Issue: notice in the browser console
```
TypeError: Cannot read properties of null (reading 'initialized')
    at set size (ids-chunk-A6WE3FK4.js:1:1255)
    at i.attributeChangedCallback (ids-chunk-64KLVD6V.js:1:697)
    at _ZoneDelegate.invoke (zone.js:368:26)
    at _Zone.runGuarded (zone.js:139:47)
    at i.attributeChangedCallback (zone.js:123:29)
    at EmulatedEncapsulationDomRenderer2.setAttribute (dom_renderer.ts:286:10)
    at setUpAttributes (attrs_utils.ts:71:18)
    at setupStaticAttributes (node_manipulation.ts:1291:5)
    at ɵɵelementStart (element.ts:163:3)
    at ResponsiveSplitterComponent_Template (responsive-splitter.component.html:17:30)
```

**Expected behavior**
1st Issue: Splitter position should be at size specified

**Version**

- ids-enterprise-wc: 1.3.0

**Screenshots**
![image](https://github.com/user-attachments/assets/febdaa8c-a0b9-43de-bedc-7ceff62723e7)

**Platform**
 - Infor Application/Team Name: Landmark
 - OS Version: Windows 11
 - Browser Name: Chrome
 - Browser Version: Latest

**Additional context**

**Comment by tmcconechy** [comment]
Putting this in if anyone can pick up @andriivarhanov @jdilag @clayinfor  ?
